apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-scaledobject
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "70"
