replicaCount: 1

image:
  repository: semitechnologies/weaviate
  pullPolicy: IfNotPresent
  tag: "1.26.0"

service:
  type: ClusterIP
  port: 8092

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
