{{- $sa := .Values.serviceAccount }}
{{- if $sa.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa.name | default (printf "%s-analytics" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: analytics
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with $sa.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $sa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
